In [38]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt


In [81]:
SIZE = (244, 244)
data = tfds.load('stanford_dogs', split='train[:80%]', as_supervised=True)
data = data.map(lambda x, y: (tf.image.resize(x, SIZE), y))\
            .map(lambda x, y: (x, tf.one_hot(y, depth=120)))\
            # .shuffle(5)

print(next(iter(data))[1])

tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(120,), dtype=float32)


In [82]:
NUM_CLASSES = 120
# data.map(lambda x, y: (x, tf.keras.utils.to_categorical([y], num_classes=NUM_CLASSES)))
for image, label in data.take(10):
    print(label)

tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(120,), dtype=float32)
tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], shape=(120,), dtype=float32)
tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [61]:
a = tf.keras.utils.to_categorical([0, 1, 2, 3, 5], num_classes=10)
# a = tf.constant(a, shape=[4, 4])
print(a)







[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [47]:
import tensorflow as tf
import tensorflow_datasets as tfds

data = tfds.load("iris",split='train[:80%]', as_supervised=True)
data = data.batch(10).map(lambda x, y: (x, tf.one_hot(y, depth=3))).repeat()

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam', 
    metrics=['categorical_accuracy'])

history = model.fit(data, steps_per_epoch=20, epochs=10)

Epoch 1/10
20/20 [==============================] - 0s 766us/step - loss: 1.2581 - categorical_accuracy: 0.3650
Epoch 2/10
20/20 [==============================] - 0s 580us/step - loss: 1.0893 - categorical_accuracy: 0.6050
Epoch 3/10
20/20 [==============================] - 0s 593us/step - loss: 1.0298 - categorical_accuracy: 0.5250
Epoch 4/10
20/20 [==============================] - 0s 560us/step - loss: 1.0055 - categorical_accuracy: 0.4600
Epoch 5/10
20/20 [==============================] - 0s 747us/step - loss: 0.9350 - categorical_accuracy: 0.4750
Epoch 6/10
20/20 [==============================] - 0s 592us/step - loss: 0.8948 - categorical_accuracy: 0.5200
Epoch 7/10
20/20 [==============================] - 0s 651us/step - loss: 0.8732 - categorical_accuracy: 0.5000
Epoch 8/10
20/20 [==============================] - 0s 695us/step - loss: 0.8248 - categorical_accuracy: 0.5300
Epoch 9/10
20/20 [==============================] - 0s 660us/step - loss: 0.7940 - categorical_accuracy: